services:
  - type: web
    name: rooms-api
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5001
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: ACCESS_TOKEN_SECRET
        sync: false
      - key: REFRESH_TOKEN_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        value: adityagptaa17@gmail.com
      - key: SMTP_PASS
        value: zeyrbdndfwbacxdd
      - key: SMTP_FROM
        value: "ROOMS <noreply@rooms.app>"
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CALLBACK_URL
        sync: false
